package com.bakeryzone.dao;

import com.bakeryzone.model.CustomCake;
import com.bakeryzone.model.CustomCakeLayerIngredient;
import com.bakeryzone.utils.DBContext;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * DAO for the custom cake builder feature.
 *
 * Responsibilities:
 *  - Save a new custom_cake header row (parent).
 *  - Save all custom_cake_layer_ingredient child rows in the same transaction.
 *  - Add the resulting entry to cart_item for the authenticated user.
 *
 * All three inserts run inside a single JDBC transaction so the database
 * is never left in a partially-written state.
 */
public class CustomCakeDAO {

    private static final Logger LOGGER = Logger.getLogger(CustomCakeDAO.class.getName());

    /**
     * Persists a custom cake and its layer-ingredient rows, then adds it to the user's cart.
     *
     * @param cake   fully-populated CustomCake (ID already generated by the servlet)
     * @param layers ordered list of layer rows (position 1 = bottom)
     * @param userId the authenticated user's ID – used for the cart_item insert
     * @return true on full success, false if any SQL step fails (transaction is rolled back)
     */
    public boolean saveCustomCakeAndAddToCart(CustomCake cake,
                                              List<CustomCakeLayerIngredient> layers,
                                              String userId) {
        Connection conn = null;
        try {
            conn = DBContext.getJDBCConnection();
            if (conn == null) {
                LOGGER.severe("CustomCakeDAO: Could not obtain a DB connection.");
                return false;
            }

            // ── Begin transaction ─────────────────────────────────────────────
            conn.setAutoCommit(false);

            // 1. Insert parent custom_cake row
            insertCustomCake(conn, cake);

            // 2. Insert child layer-ingredient rows
            insertLayerIngredients(conn, layers);

            // 3. Insert into cart_item (1 unit of this custom cake for the user)
            insertCartItem(conn, cake.getCustomCakeId(), userId, null, 1);

            conn.commit();
            return true;

        } catch (SQLException e) {
            LOGGER.log(Level.SEVERE, "CustomCakeDAO: Transaction failed, rolling back.", e);
            if (conn != null) {
                try {
                    conn.rollback();
                } catch (SQLException rollbackEx) {
                    LOGGER.log(Level.SEVERE, "CustomCakeDAO: Rollback also failed.", rollbackEx);
                }
            }
            return false;
        } finally {
            if (conn != null) {
                try {
                    conn.setAutoCommit(true); // Restore connection state before returning to pool
                    conn.close();
                } catch (SQLException closeEx) {
                    LOGGER.log(Level.WARNING, "CustomCakeDAO: Failed to close connection.", closeEx);
                }
            }
        }
    }

    // ── Private helpers ────────────────────────────────────────────────────────

    private void insertCustomCake(Connection conn, CustomCake cake) throws SQLException {
        String sql = "INSERT INTO custom_cake "
                   + "(Custom_Cake_ID, Canvas_Image_URL, Greeting_Text, Cake_Hash_Structure, Calculated_Price) "
                   + "VALUES (?, ?, ?, ?, ?)";

        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, cake.getCustomCakeId());
            ps.setString(2, cake.getCanvasImageUrl());
            ps.setString(3, cake.getGreetingText());
            ps.setString(4, cake.getCakeHashStructure());
            ps.setDouble(5, cake.getCalculatedPrice());
            ps.executeUpdate();
        }
    }

    private void insertLayerIngredients(Connection conn,
                                        List<CustomCakeLayerIngredient> layers) throws SQLException {
        String sql = "INSERT INTO custom_cake_layer_ingredient "
                   + "(Custom_Cake_ID, Layer_Position, Ingredient_ID, Quantity_Used) "
                   + "VALUES (?, ?, ?, ?)";

        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            for (CustomCakeLayerIngredient layer : layers) {
                ps.setString(1, layer.getCustomCakeId());
                ps.setInt(2, layer.getLayerPosition());
                ps.setString(3, layer.getIngredientId());
                ps.setDouble(4, layer.getQuantityUsed());
                ps.addBatch();
            }
            ps.executeBatch();
        }
    }

    private void insertCartItem(Connection conn, String customCakeId, String userId, String productId, int quantity) throws SQLException {
        // ID must match CartItemDTO.VALID_ID_PATTERN: ^CRT-[A-Z0-9\-]+$
        String cartItemId = "CRT-" + java.util.UUID.randomUUID().toString().toUpperCase();

        String sql = "INSERT INTO cart_item (Cart_Item_ID, User_ID, Custom_Cake_ID, Product_ID, Quantity, Added_At) "
                   + "VALUES (?, ?, ?, ?, ?, ?)";

        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, cartItemId);
            ps.setString(2, userId);
            
            // Custom_Cake_ID can be null for standard products
            if (customCakeId != null) {
                ps.setString(3, customCakeId);
            } else {
                ps.setNull(3, java.sql.Types.VARCHAR);
            }
            
            // Product_ID can be null for custom cakes
            if (productId != null) {
                ps.setString(4, productId);
            } else {
                ps.setNull(4, java.sql.Types.VARCHAR);
            }
            
            ps.setInt(5, quantity);
            
            // Handle Added_At (or let DB handle default via CURRENT_TIMESTAMP if preferred)
            ps.setTimestamp(6, new java.sql.Timestamp(System.currentTimeMillis()));
            
            ps.executeUpdate();
        }
    }
}
